// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2gpY4-W69VCkjnOD_4D77kHPI4tIuLy4',
    appId: '1:33421501105:web:82a9f627c3e4b64d72f890',
    messagingSenderId: '33421501105',
    projectId: 'flutterfirebasetestproject1',
    authDomain: 'flutterfirebasetestproject1.firebaseapp.com',
    storageBucket: 'flutterfirebasetestproject1.appspot.com',
    measurementId: 'G-Q6W9F5VCXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB85s6jz5hxrRmbwH7yIWCa_fVyMdgcfuA',
    appId: '1:33421501105:android:959a846fb4f4eaac72f890',
    messagingSenderId: '33421501105',
    projectId: 'flutterfirebasetestproject1',
    storageBucket: 'flutterfirebasetestproject1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmo1RnQbF7Gv3HnohBhC5tUcIGu3-pdh8',
    appId: '1:33421501105:ios:fec9801e562b23ad72f890',
    messagingSenderId: '33421501105',
    projectId: 'flutterfirebasetestproject1',
    storageBucket: 'flutterfirebasetestproject1.appspot.com',
    iosClientId: '33421501105-f24sooqfdiun5i1trn43p92sgqqoifuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebasetestproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmo1RnQbF7Gv3HnohBhC5tUcIGu3-pdh8',
    appId: '1:33421501105:ios:6f49a09f43fffdd772f890',
    messagingSenderId: '33421501105',
    projectId: 'flutterfirebasetestproject1',
    storageBucket: 'flutterfirebasetestproject1.appspot.com',
    iosClientId: '33421501105-22thab12r6kq9j7jq54jvcmcp9to2rar.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebasetestproject.RunnerTests',
  );
}
